packages:
  - apps/*
  - packages/*

catalog:
  '@better-auth/expo': 1.4.9
  '@convex-dev/better-auth': ^0.10.9
  better-auth: 1.4.9
<<<<<<< Updated upstream
  "@convex-dev/better-auth": ^0.10.9
  "@better-auth/expo": 1.4.9


allowedBuildScripts:
  - esbuild
  - msw
=======
  convex: ^1.31.2
  dotenv: ^17.2.2
  typescript: ^5
  zod: 4.3.5
>>>>>>> Stashed changes
